[project]
name = "mira-cli"
version = "0.1.0"
description = "A CLI tool for MIRA project"
dependencies = []
requires-python = ">=3.8,<3.12"

[tool.setuptools.packages.find]
where = ["."]
include = ["mira_cli*"]
